/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._login;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.general.Util;
import java.util.Map;
import java.util.HashMap;
import weaver.general.StaticObj;
import weaver.hrm.settings.RemindSettings;
import weaver.general.GCONST;
import weaver.hrm.User;
import weaver.hrm.HrmUserVarify;
import weaver.hrm.OnLineMonitor;
import weaver.systeminfo.template.UserTemplate;

public class _verifylogin__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=GBK");
    request.setCharacterEncoding("GBK");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.conn.RecordSet rsExtend;
      rsExtend = (weaver.conn.RecordSet) pageContext.getAttribute("rsExtend");
      if (rsExtend == null) {
        rsExtend = new weaver.conn.RecordSet();
        pageContext.setAttribute("rsExtend", rsExtend);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.conn.RecordSet rs;
      rs = (weaver.conn.RecordSet) pageContext.getAttribute("rs");
      if (rs == null) {
        rs = new weaver.conn.RecordSet();
        pageContext.setAttribute("rs", rs);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.conn.RecordSet RecordSet1;
      RecordSet1 = (weaver.conn.RecordSet) pageContext.getAttribute("RecordSet1");
      if (RecordSet1 == null) {
        RecordSet1 = new weaver.conn.RecordSet();
        pageContext.setAttribute("RecordSet1", RecordSet1);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.docs.docs.DocCheckInOutUtil DocCheckInOutUtil;
      DocCheckInOutUtil = (weaver.docs.docs.DocCheckInOutUtil) pageContext.getAttribute("DocCheckInOutUtil");
      if (DocCheckInOutUtil == null) {
        DocCheckInOutUtil = new weaver.docs.docs.DocCheckInOutUtil();
        pageContext.setAttribute("DocCheckInOutUtil", DocCheckInOutUtil);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      weaver.login.dactylogramCompare dactylogramCompare;
      dactylogramCompare = (weaver.login.dactylogramCompare) pageContext.getAttribute("dactylogramCompare");
      if (dactylogramCompare == null) {
        dactylogramCompare = new weaver.login.dactylogramCompare();
        pageContext.setAttribute("dactylogramCompare", dactylogramCompare);
      }
      out.write(_jsp_string3, 0, _jsp_string3.length);
      weaver.login.VerifyLogin VerifyLogin;
      VerifyLogin = (weaver.login.VerifyLogin) pageContext.getAttribute("VerifyLogin");
      if (VerifyLogin == null) {
        VerifyLogin = new weaver.login.VerifyLogin();
        pageContext.setAttribute("VerifyLogin", VerifyLogin);
      }
      out.write(_jsp_string3, 0, _jsp_string3.length);
      weaver.login.VerifyPasswdCheck VerifyPasswdCheck;
      VerifyPasswdCheck = (weaver.login.VerifyPasswdCheck) pageContext.getAttribute("VerifyPasswdCheck");
      if (VerifyPasswdCheck == null) {
        VerifyPasswdCheck = new weaver.login.VerifyPasswdCheck();
        pageContext.setAttribute("VerifyPasswdCheck", VerifyPasswdCheck);
      }
      out.write(_jsp_string4, 0, _jsp_string4.length);
      

String loginfile = Util.null2String(request.getParameter("loginfile")) ;
String logintype = Util.null2String(request.getParameter("logintype")) ;
String loginid = Util.null2String(request.getParameter("loginid")) ;
String forwardpage = Util.null2String(request.getParameter("forwardpage")) ;
String userpassword = Util.null2String(request.getParameter("userpassword"));
String message = Util.null2String(request.getParameter("message"));
String isIE = Util.null2String(request.getParameter("isie"));
if(!isIE.equals("false")){
	isIE = "true";
}
session.setAttribute("browser_isie",isIE);
//xiaofeng
int  islanguid = 7;//\u7cfb\u7edf\u4f7f\u7528\u8bed\u8a00,\u672a\u4f7f\u7528\u591a\u8bed\u8a00\u7684\u7528\u6237\u9ed8\u8ba4\u4e3a\u4e2d\u6587\u3002
String languid= "7";
boolean ismutilangua = false;
StaticObj staticobj = null;
staticobj = StaticObj.getInstance();
String multilanguage = (String)staticobj.getObject("multilanguage") ;
if(multilanguage == null) {
	VerifyLogin.checkLicenseInfo();
	multilanguage = (String)staticobj.getObject("multilanguage") ;
}else if(multilanguage.equals("y")){
	ismutilangua = true;
}
boolean isSyadmin=true;
//\u5224\u65ad\u5206\u6743\u7ba1\u7406\u5458
String Sysmanager = "select loginid from hrmresourcemanager where loginid = '"+loginid+"'";
RecordSet1.executeSql(Sysmanager);
if(RecordSet1.next()){
	isSyadmin = false;
}
if(loginid.equalsIgnoreCase("sysadmin")){
	isSyadmin = false;
}
if(isSyadmin){
	if(ismutilangua){
			islanguid = Util.getIntValue(request.getParameter("islanguid"),0);
				if(islanguid == 0){//\u5982\u4f55\u672a\u9009\u62e9\uff0c\u5219\u9ed8\u8ba4\u7cfb\u7edf\u4f7f\u7528\u8bed\u8a00\u4e3a\u7b80\u4f53\u4e2d\u6587
					islanguid = 7;
				}
		languid = String.valueOf(islanguid); 
		Cookie syslanid = new Cookie("Systemlanguid",languid);
		syslanid.setMaxAge(-1);
		syslanid.setPath("/");
		response.addCookie(syslanid);
	}
}/*else{
	Cookie syslanid = new Cookie("Systemlanguid",languid);
	syslanid.setMaxAge(-1);
	syslanid.setPath("/");
	response.addCookie(syslanid);
}*/
String serial=Util.null2String(request.getParameter("serial"));
String username = Util.null2String(request.getParameter("username"));
String rnd=Util.null2String(request.getParameter("rnd"));
String loginPDA=Util.null2String(request.getParameter("loginPDA"));
session.setAttribute("loginPAD",loginPDA);
String RedirectFile="/main.jsp"; 
if(!"".equals(forwardpage))
{
	RedirectFile = forwardpage;
}
if (loginPDA.equals("1"))
{
RedirectFile= "/mainPDA.jsp";
}
//add by sean.yang 2006-02-09 for TD3609
String validatecode=Util.null2String(request.getParameter("validatecode"));

//modify by mackjoe at 2005-11-28 td3282 \u90ae\u4ef6\u63d0\u9192\u767b\u9646\u540e\u76f4\u63a5\u5230\u6307\u5b9a\u6d41\u7a0b
String gopage=Util.null2String(request.getParameter("gopage"));
if(!"".equals(gopage) && !gopage.contains("main.jsp")){
	session.setAttribute("gopageOrientation",gopage);
}
if(gopage.trim().equals("")&&session.getAttribute("gopages")!=null)
{
	try{
		gopage = (String)session.getAttribute("gopages");
		session.removeAttribute("gopages");
	}catch(Exception e){}
}
if(gopage.length()>0){
    RedirectFile = "/main.jsp?gopage="+gopage ;
}
if (loginfile.equals("")) loginfile="/login/Login.jsp?logintype="+logintype+"&gopage="+gopage;
//end by mackjoe
// modify by dongping for TD1340 in 2004.11.05
// \u7528\u6237\u767b\u9646\u65f6\u8981\u5bf9cookies\u662f\u5426\u5f00\u653e\u4f5c\u5224\u65ad\uff0c\u5982\u679c\u6ca1\u6709\uff0c\u5219\u4f1a\u7ed9\u51fa\u63d0\u793a!
String logincookid = Util.getEncrypt(loginid);
String testcookie = "";
if (!loginPDA.equals("1")){//\u624b\u673a\u767b\u9646\u4e0d\u8981\u963b\u6b62cookie
	testcookie = new java.util.Date().getTime()+"+"+logincookid;

      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((testcookie));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
}
String dactylogram = Util.null2String(request.getParameter("dactylogram"));//\u6307\u7eb9\u7279\u5f81
boolean compareFlag = false;
if(!dactylogram.equals("")){

	//String dactylogramOfCookie = Util.null2String(Util.getCookie(request,"dactylogram"));
	//String assistantDactylogramOfCookie = Util.null2String(Util.getCookie(request,"assistantdactylogram"));
	//if(!dactylogramOfCookie.equals("")) dactylogramCompare.setCookieDactylogram(dactylogramOfCookie);
	//if(!assistantDactylogramOfCookie.equals("")) dactylogramCompare.setCookieAssistantDactylogram(assistantDactylogramOfCookie);
	
	compareFlag = dactylogramCompare.executeCompare(dactylogram);
	if(compareFlag){
		loginid = dactylogramCompare.getLoginId();
		userpassword = dactylogramCompare.getPassword();
		logintype = "1";
	}else{
		response.sendRedirect("/login/Login.jsp?&message=nomatch") ;
		return;
	}
}

if (logintype.equals("2")){
	if(!gopage.equals("")){
 		RedirectFile = "/portal/main.jsp?gopage="+gopage ;
	}else{
		RedirectFile = "/portal/main.jsp" ;
	}
}

String tourl = "";
if(loginid.equals("") || userpassword.equals("") ) response.sendRedirect(loginfile + "&message=18") ;
else  { RemindSettings settings=(RemindSettings)application.getAttribute("hrmsettings");
    String needusb=settings.getNeedusb();
	String usercheck ;
	String notusbusercheck = "";
	if(compareFlag){
		usercheck= VerifyLogin.getUserCheckByDactylogram(request,response,loginid,userpassword,logintype,loginfile,validatecode,message,languid,ismutilangua);
	}else{
		boolean canpass = VerifyPasswdCheck.getUserCheck(loginid,"",1);
		if(!canpass){
			if(needusb!=null&&needusb.equals("1")){
				notusbusercheck= VerifyLogin.getUserCheck(request,response,loginid,userpassword,logintype,loginfile,validatecode,message,languid,ismutilangua);
				request.getSession(true).removeAttribute("weaver_user@bean");
				
				usercheck= VerifyLogin.getUserCheck(request,response,loginid,userpassword,serial,username,rnd,logintype,loginfile,validatecode,message,languid,ismutilangua);
			
			}else{
				usercheck= VerifyLogin.getUserCheck(request,response,loginid,userpassword,logintype,loginfile,validatecode,message,languid,ismutilangua);
			}
		}else{
			usercheck = "110";
		}
	}
	VerifyPasswdCheck.getUserCheck(loginid,usercheck,2);
	if(usercheck.equals("15")|| usercheck.equals("57") || usercheck.equals("17")|| usercheck.equals("45")|| usercheck.equals("46")|| usercheck.equals("47")|| usercheck.equals("52")|| usercheck.equals("55"))
    {
        String tmploginid=(String)session.getAttribute("tmploginid");
        if(tmploginid!=null&&loginid.equals(tmploginid))
           session.setAttribute("tmploginid1",loginid);
        else
           session.removeAttribute("tmploginid");
        response.sendRedirect(loginfile + "&message="+usercheck) ;
	}else if(usercheck.equals("16")){
		String usbMsgparam = "";
		if(needusb!=null&&needusb.equals("1") && !"16".equals(notusbusercheck)){
			if (!"0".equals(serial)) {
				usbMsgparam = "&usbparammsg=1";
			}
		}
		request.getSession(true).removeAttribute("weaver_user@bean");
		session.setAttribute("tmploginid1",loginid);
		response.sendRedirect(loginfile + "&message="+usercheck + usbMsgparam) ;
	}else if(usercheck.equals("19")){
		response.sendRedirect("/system/InLicense.jsp") ;
	} else if (usercheck.equals("26")) {
		if (!loginPDA.equals("1")) {
			response.sendRedirect("/login/Login.jsp?logintype=1&message="+usercheck);
		} else {
			response.sendRedirect("/login/LoginPDA.jsp?logintype=1&message="+usercheck);
		}
	}else if(usercheck.equals("101")){
        session.setAttribute("tmploginid",loginid);
        session.setAttribute("tmploginid1",loginid);
        if (!loginPDA.equals("1")) {
        response.sendRedirect("/login/Login.jsp?logintype=1&message="+usercheck) ;
		}
		else
		{
		response.sendRedirect("/login/LoginPDA.jsp?logintype=1&message="+usercheck) ;
		}
    }
    else if(usercheck.equals("110"))
	{
		if (!loginPDA.equals("1"))
		{
			response.sendRedirect("/login/Login.jsp?logintype=1&message=" + usercheck);
		}
		else
		{
			response.sendRedirect("/login/LoginPDA.jsp?logintype=1&message=" + usercheck);
		}
	}else if(usercheck.equals("122")){   //\u52a8\u6001\u5bc6\u7801\u9519\u8bef
		response.sendRedirect("/login/Login.jsp?logintype=1&message=" + usercheck);
	}
	else if(usercheck.equals("120")){    //\u672a\u7ed1\u5b9a\u52a8\u6001\u4ee4\u724c
		response.sendRedirect("/login/bindTokenKey.jsp");
	}
	else {
            if("1".equals(session.getAttribute("istest"))){
                session.removeAttribute("istest");
            }
            User user = HrmUserVarify.getUser (request , response) ;
            if(user == null) { response.sendRedirect(loginfile ) ; return;}

            session.setAttribute("password",userpassword);
            if("1".equals(logintype)){
            session.setAttribute("moniter", new OnLineMonitor("" + user.getUID(),user.getLoginip(),application));
            }
            Map logmessages=(Map)application.getAttribute("logmessages");
                if(logmessages==null){
                logmessages=new HashMap();
                logmessages.put(""+user.getUID(),"");
                application.setAttribute("logmessages",logmessages);
                }
	        session.setAttribute("logmessage",usercheck);
	        session.setAttribute("fromlogin","yes");
            session.removeAttribute("tmploginid");

            DocCheckInOutUtil.docCheckInWhenVerifyLogin(user,request);

		//\u5c0f\u7a97\u53e3\u767b\u5f55 (TD 2227)
		//hubo,050707
		if(request.getSession(true).getAttribute("layoutStyle")!=null && request.getSession(true).getAttribute("layoutStyle").equals("1")){
			session.setAttribute("istimeout","no");

      out.write(_jsp_string7, 0, _jsp_string7.length);
      
		}else{
			if (loginPDA.equals("1")){
				response.sendRedirect(RedirectFile) ;
				return;
			}
			if("2".equals(logintype)){
				response.sendRedirect(RedirectFile) ;
				return;
			} else {
				
				
				UserTemplate  ut=new UserTemplate();
				
				ut.getTemplateByUID(user.getUID(),user.getUserSubCompany1());
				int templateId=ut.getTemplateId();
				int extendTempletid=ut.getExtendtempletid();
				int extendtempletvalueid=ut.getExtendtempletvalueid();
				String defaultHp = ut.getDefaultHp();
				session.setAttribute("defaultHp",defaultHp);
				
				if(extendTempletid!=0){
					rsExtend.executeSql("select id,extendname,extendurl from extendHomepage  where id="+extendTempletid);
					if(rsExtend.next()){
						int id=Util.getIntValue(rsExtend.getString("id"));
						//String extendname=Util.null2String(rsExtend.getString("extendname"));	
						String extendurl=Util.null2String(rsExtend.getString("extendurl"));	
						rs.executeSql("select * from extendHpWebCustom where templateid="+templateId);
						String defaultshow ="";
						if(rs.next()){
							defaultshow = Util.null2String(rs.getString("defaultshow"));
						}
						String param = "";
						if(!defaultshow.equals("")){
							param ="&"+defaultshow.substring(defaultshow.indexOf("?")+1);
						}
						if(gopage.length()>0){
							tourl = "/login/RemindLogin.jsp?RedirectFile="+extendurl+"/index.jsp?templateId="+templateId+param+"&gopage="+gopage;
						}else{			
							tourl = "/login/RemindLogin.jsp?RedirectFile="+extendurl+"/index.jsp?templateId="+templateId+param;
						}
						//tourl = extendurl+"/index.jsp?templateId="+templateId+param;
						//response.sendRedirect(extendurl+"/index.jsp?templateId="+templateId+param) ;
						//return;		
					}
				} else {
					//tourl = RedirectFile;
					tourl = "/login/RemindLogin.jsp?RedirectFile="+RedirectFile;
					//response.sendRedirect(RedirectFile) ;
					//return;
				}
			}
		}
	}
}
//\u624b\u673a\u4e0d\u68c0\u6d4b
if (!loginPDA.equals("1")){

      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((testcookie));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((logintype));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((tourl));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((logintype));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      
}
else {
	response.sendRedirect(tourl) ;
	return;
}

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("login/VerifyLogin.jsp"), -822379463671498983L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string9;
  private final static char []_jsp_string10;
  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  private final static char []_jsp_string12;
  private final static char []_jsp_string8;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string11;
  static {
    _jsp_string9 = "')==-1) {\r\n		document.location.href = '/login/Login.jsp?logintype=".toCharArray();
    _jsp_string10 = "&noAllowIe=yes';\r\n	}\r\n	else {\r\n		document.location.href = '".toCharArray();
    _jsp_string7 = "\r\n			<SCRIPT LANGUAGE=VBS>\r\n				window.parent.returnvalue = \"1\"\r\n				window.parent.close\r\n			</script>\r\n".toCharArray();
    _jsp_string2 = "\r\n	\r\n".toCharArray();
    _jsp_string12 = "&noAllowIe=yes';\r\n}\r\n</script>\r\n".toCharArray();
    _jsp_string8 = "\r\n<script>\r\ntry {\r\n	if(document.cookie.indexOf('logincookiecheck=".toCharArray();
    _jsp_string5 = "\r\n<script>\r\ndocument.cookie='logincookiecheck=".toCharArray();
    _jsp_string6 = "';\r\n</script>\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string3 = " \r\n".toCharArray();
    _jsp_string4 = "\r\n\r\n".toCharArray();
    _jsp_string11 = "';\r\n	}\r\n}\r\ncatch(e){\r\n	document.location.href = '/login/Login.jsp?logintype=".toCharArray();
  }
}
